spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: ${ES_IP_PORT:47.92.107.76:10022}
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录
  application:
    name: ec_server_schedels
  profiles:
    active: ${ENV:dev}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy #命名策略，加分隔线"_"

main:
  server-url: ${SERVER-URL:http://localhost:8080}  #要访问后台的地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_SERVER:localhost:8080}/eureka/