spring:
  datasource:
    primary:
      url: jdbc:mysql://47.92.159.54:3306/company_bak?autoReconnect=true&useUnicode=true&useSSL=false
      username: root
      password: MAIda6868#
    secondary:
      url: jdbc:mysql://47.92.159.54:3306/ec_server_bak?autoReconnect=true&useUnicode=true&useSSL=false
      username: root
      password: MAIda6868#
    thirdly:
      url: jdbc:mysql://47.92.159.54:3306/scrapy_bak?autoReconnect=true&useUnicode=true&useSSL=false
      username: root
      password: MAIda6868#
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 10000