spring:
  datasource:
    primary:
      url: jdbc:mysql://5996933a901a7.bj.cdb.myqcloud.com:5326/company?autoReconnect=true&useUnicode=true
      username: root
      password: Wu@0396110
    secondary:
      url: jdbc:mysql://5996933a901a7.bj.cdb.myqcloud.com:5326/ec_server?autoReconnect=true&useUnicode=true
      username: root
      password: Wu@0396110