spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/company?autoReconnect=true&useUnicode=true
      username: root
      password: root
    secondary:
      url: jdbc:mysql://localhost:3306/ec_server?autoReconnect=true&useUnicode=true
      username: root
      password: root
    thirdly:
      url: jdbc:mysql://localhost:3306/scrapy?autoReconnect=true&useUnicode=true
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 10000